WIP: [Gaps-161] : Data Migration
django-cms/djangocms-url-manager pull request #62
Opened 2021-11-19 15:01 UTC by Bernardvdv

- Migration file added to migrate content from Url to Url Grouper

2021-11-22 09:02 UTC, adam-murray requested changes
We are missing the plugin migration at the moment. 
https://github.com/django-cms/djangocms-snippet/blob/aa450b38ba69ff96b30d52fef80f3f380e5e0f4a/djangocms_snippet/migrations/0011_cms4_plugin_data_migration.py#L5

2021-11-22 11:22 UTC, adam-murray commented on djangocms_url_manager/migrations/0008_url_manager_data_migration.py
> +    for url in url_queryset:
I think we will need another migration for the UrlOverride as well.

2021-11-23 14:29 UTC, Aiky30 requested changes

2021-11-23 14:29 UTC, Aiky30 commented on djangocms_url_manager/migrations/0009_url_manager_data_migration.py
> +    DJANGOCMS_URL_MANAGER_VERSIONING_MIGRATION_USER_ID,
This setting needs documenting in the documentation in this repo.

2021-11-23 14:29 UTC, Aiky30 commented on djangocms_url_manager/models.py
> +    internal_name = models.CharField(verbose_name=_("internal name"), max_length=120)
```suggestion
```

We can remove all existence of the internal name on the plugin, it's a redundant field that was a mistake a long time ago. It has no use in the system. I've been waiting for the day when the plugin model was changed to edit this. It was a requirement for urls to allow you to find them in the system, they have no purpose on the plugin.

If you delete this field and the migration 11 file, rerun the makemigrations command and the deletions will be captured automatically.

2021-11-23 14:29 UTC, Aiky30 commented on djangocms_url_manager/migrations/0009_url_manager_data_migration.py
> +    create_contenttypes(global_apps.get_app_config("djangocms_url_manager"))
```suggestion
```

You shouldn't need to create the content type, django takes care of this when loading up.

2021-11-23 17:11 UTC, adam-murray approved these changes

2021-11-24 11:26 UTC, adam-murray approved these changes

2022-01-14 11:01 UTC, closed without merging