Gaps 162 forms views
django-cms/djangocms-url-manager pull request #69
Opened 2021-11-27 14:34 UTC by adam-murray

2021-11-29 11:39 UTC, Aiky30 requested changes
I've not looked into the test changes in depth yet. We are missing a lot of tests for versioning, i..e all fo the tests in place currently test live views, we need to add tests that cover edit / preview views for draft content too.

2021-11-29 11:39 UTC, Aiky30 commented on djangocms_url_manager/views.py
> +        queryset = Url._base_manager.all()
URL is the content object, this will show multiple entries for the same grouper. Alias does this pretty well where the user is shown (Draft) and (Published) flags by the entries, there will be tests in Alias for this too, may be worth copying the tests over first and build this TDD:

<img width="1792" alt="Screenshot 2021-11-29 at 11 30 40" src="https://user-images.githubusercontent.com/12543977/143860880-ad626a83-bd54-4109-8571-80241becf842.png">


<img width="1792" alt="Screenshot 2021-11-29 at 11 35 08" src="https://user-images.githubusercontent.com/12543977/143861095-2a9e42de-86c6-49aa-adf5-e417728e5de5.png">

2021-11-29 11:39 UTC, Aiky30 commented on setup.py
> +    "djangocms-attributes-field",  # django 1.11 compat
Redundant comment

```suggestion
    "djangocms-attributes-field", 
```

2021-11-29 11:39 UTC, Aiky30 commented on tests/test_forms.py
> -    def test_url_override_form(self):
Why has this test been removed? The skip should be removed not the entire test.

2021-11-29 11:39 UTC, Aiky30 commented on tests/test_forms.py
> -    def test_url_override_form_disallow_same_site_as_original_url(self):
Why has this test been removed? The skip should be removed not the entire test.

2021-11-29 11:39 UTC, Aiky30 commented on tests/test_forms.py
> -    def test_url_override_form_dont_validate_object_already_exists(self):
Why has this test been removed? The skip should be removed not the entire test.

2021-11-29 11:39 UTC, Aiky30 commented on tests/test_forms.py
> -    def test_url_override_form_validate_object_with_this_site_and_object_already_exists(
Why has this test been removed? The skip should be removed not the entire test.

2021-11-30 15:49 UTC, Aiky30 commented on djangocms_url_manager/migrations/0008_url_manager_data_migration.py
> +        migration_user = User.objects.get(id=DJANGOCMS_URL_MANAGER_VERSIONING_MIGRATION_USER_ID)
This preforms a query for the same user for the loop, it's only needed if versioning is enabled, this should be similar to snippets:

https://github.com/django-cms/djangocms-snippet/blob/support/django-cms-4.0.x/djangocms_snippet/migrations/0010_cms4_grouper_version_data_migration.py#L37

2021-11-30 15:52 UTC, Aiky30 commented on djangocms_url_manager/models.py
> +        # TODO: Check the results of this method with ARCHIVED etc.
```suggestion
```

Archived won't be rendered so not an issue.

2021-11-30 17:38 UTC, Aiky30 requested changes
Some minor changes.

Not looking at the tests yet.

2021-11-30 17:38 UTC, Aiky30 commented on djangocms_url_manager/migrations/0008_url_manager_data_migration.py
> +    migration_user = User.objects.get(id=DJANGOCMS_URL_MANAGER_VERSIONING_MIGRATION_USER_ID)
The logic from Snippets hasn't been fully brought over, this should only happen if versioning is enabled:

https://github.com/django-cms/djangocms-snippet/blob/55abe6730982220fdcbd3785aa20ada4b6ed1821/djangocms_snippet/migrations/0010_cms4_grouper_version_data_migration.py#L34

Version below should be here:

```python
if djangocms_versioning_config_enabled and djangocms_versioning_installed and len(url_queryset):
    migration_user = User.objects.get(id=DJANGOCMS_URL_MANAGER_VERSIONING_MIGRATION_USER_ID)
    Version = apps.get_model('djangocms_versioning', 'Version')
```

2021-11-30 17:38 UTC, Aiky30 commented on djangocms_url_manager/forms.py
> +        # TODO: Replace url
```suggestion
```

Redundant comment, url is required here

2021-11-30 17:38 UTC, Aiky30 commented on djangocms_url_manager/forms.py
> +        base_fields = UrlForm.Meta.fields
Reverse the changes to this:

```suggestion
        fields = ("url",) + UrlForm.Meta.fields
```

2021-11-30 17:38 UTC, Aiky30 commented on djangocms_url_manager/forms.py
> +        fields = ("url",) + base_fields
```suggestion
```

With the above changes this can be removed

2021-11-30 18:15 UTC, Aiky30 commented on djangocms_url_manager/templatetags/djangocms_url_manager_tags.py
> +    url = instance.url_grouper.url(toolbar.preview_mode_active)
```suggestion
    url = instance.url_grouper.get_content(toolbar.preview_mode_active)
```

2021-11-30 18:55 UTC, Aiky30 commented on djangocms_url_manager/templatetags/djangocms_url_manager_tags.py
> +    url = instance.get_content(toolbar.preview_mode_active)
This is missing the edit check and we're still not handling if url is None
```
        # Get draft contents in edit or preview mode?
        show_draft_content = False
        if toolbar.edit_mode_active or toolbar.preview_mode_active:
            show_draft_content = True

        url = instance.get_content(show_draft_content)

        if not url:
            return ""
```

2021-11-30 19:07 UTC, Aiky30 commented on djangocms_url_manager/templatetags/djangocms_url_manager_tags.py
> +    return url.get_url(renderer.current_site) or ""
```suggestion
    return url.get_url(renderer.current_site)
```

2021-12-01 09:14 UTC, Aiky30 commented on djangocms_url_manager/templates/admin/djangocms_url_manager/url/change_form.html
> +{% extends is_versioning_enabled|yesno:"djangocms_versioning/admin/mixins/change_form.html,admin/change_form.html" %}
```suggestion
{% extends is_versioning_enabled|yesno:"djangocms_versioning/admin/mixin/change_form.html,admin/change_form.html" %}
```

This seems to have rolled back to the original with the wrong path for mixins

2021-12-01 11:18 UTC, Aiky30 commented on djangocms_url_manager/forms.py
> +            self.fields["url_grouper"].initial = self.instance.url_grouper.url()
```suggestion
            self.fields["url_grouper"].initial = self.instance.url_grouper_id
```
Tested this change on my local/

2022-01-07 09:21 UTC, closed without merging

2022-01-07 09:22 UTC, adam-murray commented
Closing as this functionality was implemented in another PR